# This is a basic workflow to help you get started with Actions

name: thebitbeta

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch and master branch
on:
  push:
    branches: [main]
    
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         contexts: [./src/auth_service,./src/frontend]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: prathyand/thebitbeta
      
      - name: Build and push authmodule
        uses: docker/build-push-action@v3
        with:
          context: ./src/auth_service/
          file: ./src/auth_service/Dockerfile
          push: true
          tags: prathyand/thebitbeta:auth_module_latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./src/frontend/
          file: ./src/frontend/Dockerfile
          push: true
          tags: prathyand/thebitbeta:frontend_latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: executing remote ssh commands using key file
        uses: appleboy/ssh-action@master
        with:
          # host for jetstream server
          host: ${{ secrets.AWS_HOST }}
          # username for jetstream server
          username: ${{ secrets.AWS_USER }}
          # jetstream userkey, added to server and github secrets
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd $HOME
            rm -rf thebitbeta/
            git clone https://github.com/prathyand/thebitbeta.git
            echo "stopping containers"
            cd thebitbeta/src
            docker compose -f docker-compose_aws.yml down  
            echo "Fetching latest docker images"
            docker compose -f docker-compose_aws.yml pull
            echo "Deploying the application"
            docker compose -f docker-compose_aws.yml up -d

